[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://inbox-ai.onrender.com"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"

# Backend URL: https://inbox-ai.onrender.com
# Frontend URL: https://inboxai-tech.netlify.app

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# API proxy to avoid CORS issues
[[redirects]]
  from = "/api/*"
  to = "https://inbox-ai.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
