#!/bin/bash

echo "🚀 InboxPrism Deployment Guide"
echo "================================"
echo ""

echo "📋 Step 1: Create GitHub Repository"
echo "1. Go to https://github.com/new"
echo "2. Repository name: InboxPrism (or EmailAgent)"
echo "3. Description: AI-powered email management and response system"
echo "4. Set to Public or Private as preferred"
echo "5. DO NOT initialize with README, .gitignore, or license (we already have these)"
echo "6. Click 'Create repository'"
echo ""

echo "📋 Step 2: Push to GitHub"
echo "Replace YOUR_USERNAME with your GitHub username:"
echo "git remote add origin https://github.com/YOUR_USERNAME/InboxPrism.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""

echo "📋 Step 3: Deploy Frontend on Vercel"
echo "1. Go to https://vercel.com/new"
echo "2. Import your GitHub repository"
echo "3. Framework Preset: Next.js"
echo "4. Root Directory: frontend"
echo "5. Add Environment Variables:"
echo "   - NEXT_PUBLIC_API_URL=https://your-backend-url.onrender.com"
echo "6. Click 'Deploy'"
echo ""

echo "📋 Step 4: Deploy Backend on Render"
echo "1. Go to https://dashboard.render.com/new/web"
echo "2. Connect your GitHub repository"
echo "3. Name: inboxprism-backend"
echo "4. Runtime: Python 3"
echo "5. Build Command: pip install -r requirements.txt"
echo "6. Start Command: uvicorn backend.api.main:app --host 0.0.0.0 --port \$PORT"
echo "7. Add Environment Variables:"
echo "   - OPENAI_API_KEY=your_openai_api_key"
echo "   - GMAIL_CLIENT_ID=your_gmail_client_id"
echo "   - GMAIL_CLIENT_SECRET=your_gmail_client_secret"
echo "   - DATABASE_URL=sqlite:///./emails.db"
echo "   - CORS_ORIGINS=https://your-frontend-url.vercel.app"
echo "8. Click 'Create Web Service'"
echo ""

echo "📋 Step 5: Update Frontend with Backend URL"
echo "After backend is deployed, update the frontend environment variable:"
echo "NEXT_PUBLIC_API_URL with your actual Render backend URL"
echo ""

echo "✅ Your InboxPrism is ready for deployment!"
echo "Repository is committed and ready to push to GitHub."
