services:
  - type: web
    name: inboxprism-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python -m uvicorn api.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: AZURE_OPENAI_API_KEY
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /
    autoDeploy: false
